### PR TITLE
make: Support 'together' action modifier

### LINKED ISSUE #40: Support `together` actions modifier
Support `actions together`, which combines multiple rule invocations on the same target into one, concatenating the source lists.

### PR DESCRIPTION
**Pull request by dominicm00**
Closes #40 

- [x] Create test
- [x] Combine actions in `Processor::_MakeTarget`
- [x] Add ADR for `together` behavior

### CODE REVIEW

**Comment by dominicm00** [comment]
This is a bit annoying to implement correctly since you can have multiple targets. The "expected" way for `together` to be used is with a single target like so:
```
rule EchoAll
{
	Depends $(1) : $(2) ;
}

actions together EchoAll
{
	echo "Built $(1) with $(2) "
}

NOTFILE source1 source2 source3 source4 ;

LOCATE on target = . ;
EchoAll target : source1 ;
EchoAll target : source2 source3 ;
EchoAll target : source4 ;

Depends all : target ;
-
$ jam
EchoAll target 
Built target with source1 source2 source3 source4 
```

But what to do if you have multiple targets? The targets can have overlapping, but not identical sources. Should you invoke rules Venn-diagram style, going through each set of targets and outputting a command for the sources they have in common? Should you reduce the commands to single targets and all their sources?

Jam did not appear to give any thought to this case and spits out nonsense:
```
rule EchoAll
{
	Depends $(1) : $(2) ;
}

actions together EchoAll
{
	echo "Built $(1) with $(2) "
}

NOTFILE source1 source2 source3 source4 ;

LOCATE on target1 = . ;
LOCATE on target2 = . ;
LOCATE on target3 = . ;
EchoAll target1 target2 : source1 ;
EchoAll target1 target2 : source2 ;
EchoAll target1 : source3 ;
EchoAll target2 : source3 ;
EchoAll target1 : source4 ;

Depends all : target1 target2 ;
-
$ jam
EchoAll target1 target2 
Built target1 target2 with source1 source2 source3 source4 
EchoAll target2 
Built target2 with source3 
```

Notice that `target2` is built with `source4` despite not depending on it, and is then rebuilt again with only `source3`; not great behavior.

My inclination is to spit out an error here. If the user wants to build targets one-by-one, they can use a for loop to apply the action to each target. And I frankly don't see any use case for the Venn-diagram style.

@stippi Can you give your thoughts here?

**Comment by stippi2** [comment]
I am actually not very familiar with the Jam language. Can you give an example of what the behavior is for the "expected way" when *not* specifying `together`. Can you make it tangible with a "real world" example of when `together` is useful? Feel free to link to existing documentation.

**Comment by dominicm00** [comment]
> I am actually not very familiar with the Jam language. Can you give an example of what the behavior is for the "expected way" when _not_ specifying `together`. Can you make it tangible with a "real world" example of when `together` is useful? Feel free to link to existing documentation.

Sure; without `together`, separate commands are made for each action invocation:
```
actions quietly EchoAll
{
	echo "Built $(1) with $(2) "
}

LOCATE on target1 = . ;
LOCATE on target2 = . ;

NOTFILE source1 source2 source3 ;

EchoAll target1 : source1 source2 ;
EchoAll target2 : source1 ;
EchoAll target2 : source2 ;
EchoAll target2 : source3 ;

Depends all : target1 target2 ;
-
$ jam
Built target1 with source1 source2 
Built target2 with source1 
Built target2 with source2 
Built target2 with source3 
```

Here, actions essentially just act as shell commands, with `$(1)` and `$(2)` being substituted with the targets and sources of each invocation, respectively. Multiple targets are easy to deal with; just put them all in `$(1)`.

With `together`, things are more murky. From the Jam docs:
> The $(>) (read: sources) from multiple invocations of the same action on the same built target are glommed together.

A common use for `together` is the `clean` target. You want to invoke `rm` on all the sources for `clean` at once, instead of one at a time.
```
actions together quietly EchoAll
{
	echo "Built $(1) with $(2) "
}

LOCATE on target1 = . ;
LOCATE on target2 = . ;

NOTFILE source1 source2 source3 ;

EchoAll target1 : source1 source2 ;
EchoAll target2 : source1 ;
EchoAll target2 : source2 ;
EchoAll target2 : source3 ;

Depends all : target1 target2 ;
-
$ jam
Built target1 with source1 source2 
Built target2 with source1 source2 source3 
```

Notice that, even though the action on `target2` was invoked several times, it's all combined into one command.

However, how do you combine by "same built target" if an action is passed multiple targets? There's a few ways to interpret it:

1. Treat the "target" to compare as the set of targets, combining invocations on identical sets.
```
EchoAll target1 target2 : source1 source2 ;
EchoAll target2 target1: source3 ;
EchoAll target1 : source4 ;
EchoAll target2 : source4 ;
-
Built target1 target2 with sources source1 source2 source3
Built target1 with sources source4
Built target2 with sources source4
```

Notice that even though `target1` and `target2` have the same set of sources, the commands are only combined when they are explicitly used together.

2. If the targets appear together in at least one invocation and have the same source set, combine them.
```
EchoAll target1 target2 target3 : source1 ;
EchoAll target1 : source2 ;
EchoAll target2 : source2 ;
-
Built target1 target2 with sources source1 source2
Built target3 with sources source1
```

3. Split target set into an invocation per target
```
EchoAll target1 target2 target3 : source1 ;
EchoAll target1 : source2 ;
EchoAll target2 : source2 ;
-
Built target1 with sources source1 source2
Built target2 with sources source1 source2
Built target3 with sources source1
```

4. Invoke the command on each combination of targets whose intersection of sources is non-empty. There are some variations on this idea but I think it's intuitive, plus it leads to exponential blow-up.
5. Throw an error.

I'm personally leaning towards 5, just because there doesn't seem to be a natural behavior and I think it's better to force the user to use rules to create an invocation pattern.

**Comment by stippi** [comment]
I think I understand the options that you outline. But I have one question about the output of option 3:

> 3\. If the targets appear together in at least one invocation and have the same source set, combine them.
> 
> ```
> EchoAll target1 target2 target3 : source1 ;
> EchoAll target1 : source2 ;
> EchoAll target2 : source2 ;
> -
> Built target1 target2 with sources source1 source2
> Built target3 with sources source1
> ```

You wrote "and have the same source set", but should that not lead to more invocations? The source sets are different for target1 and target2 where they appear.

In any case, if there are good arguments for 5, then go for it. You can always revisit this later if more information becomes available.

**Comment by stippi** [comment]
Maybe one more thought: If a `target` is one unique build result, i.e. building it multiple times would overwrite it, then I maybe an interpretation makes sense that leads to unique targets being built only once. Such as option 2) or maybe 3), unless I am right with my question above. (I know a target could also mean a pseudo target where nothing actually gets overwritten, but it represents a unique "entity" that other targets can depend on.) There should only be one production of that entity. But you are way deeper into this than I, so I could well be missing something.

**Comment by dominicm00** [comment]
> You wrote "and have the same source set", but should that not lead to more invocations? The source sets are different for target1 and target2 where they appear.
> 
> In any case, if there are good arguments for 5, then go for it. You can always revisit this later if more information becomes available.

I'm not sure I understand; both target1 and target2 depend on the set source1, source2. Am I missing something here?

> Maybe one more thought: If a target is one unique build result, i.e. building it multiple times would overwrite it, then maybe an interpretation makes sense that leads to unique targets being built only once. Such as option 2) or maybe 3), unless I am right with my question above.

I think this is the most natural interpretation. It also works with the other interpretation of targets as "marking" sources for an action (we'd want to enact the action once on each source file).

I think, at least for now, I will go with an error because it's potentially confusing, and the behavior of 3 (one invocation per target) is trivial to replicate with a for loop.

**Comment by dominicm00** [comment]
This is turning out to be much, much harder than it has any right to be because the `const`ness of the data structured needed is incompatible.

**Comment by dominicm00** [comment]
I missed where `Target`s were being made const, and was able to temporarily get the code working by removing the const modifiers where needed.

**Comment by stippi2** [comment]
Hi! You already merged this PR shortly after requesting my review. Is it still wanted?

**Comment by dominicm00** [comment]
> Hi! You already merged this PR shortly after requesting my review. Is it still wanted?

Ah, sorry, I think it's all good now; I'll be more careful assigning you to PRs.

**Pull request merged**
